### ISSUE TITLE
Can't load XML resource

### ISSUE THREAD

**Issue by bgrainger** [farlee2121/ResXResourceReader.NetStandard#5]
When an XML file is added to Resources in Visual Studio, the following XML is stored in the resx file:

```xml
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="Test" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>Test.xml;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8</value>
  </data>
```

Trying to load this data (in a `net7.0` application) throws the following exception:

```
System.ArgumentException: ResX file Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. Line 8015, position 5. cannot be parsed.
 ---> System.Xml.XmlException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. Line 8015, position 5.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Resources.NetStandard.AssemblyNamesTypeResolutionService.GetAssembly(AssemblyName name, Boolean throwOnError)
   at System.Resources.NetStandard.AssemblyNamesTypeResolutionService.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Resources.NetStandard.ResXDataNode.InitializeDataNode(String basePath)
   at System.Resources.NetStandard.ResXDataNode..ctor(DataNodeInfo nodeInfo, String basePath)
   at System.Resources.NetStandard.ResXResourceReader.ParseDataNode(XmlTextReader reader, Boolean isMetaData)
   at System.Resources.NetStandard.ResXResourceReader.ParseXml(XmlTextReader reader)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Resources.NetStandard.ResXResourceReader.ParseXml(XmlTextReader reader)
   at System.Resources.NetStandard.ResXResourceReader.EnsureResData()
   at System.Resources.NetStandard.ResXResourceReader.GetEnumerator()
```

It seems like this could work if ResXResourceReader.NetStandard used its own implementation of `ResXFileRef` instead of trying to load the WinForms one.

**Comment by farlee2121** [comment]
Thanks for the PR! I'll give it a look
